repos:
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        language_version: python3
        name: 🎨 Format code with Black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: 📦 Sort imports with isort

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        name: 🔍 Lint with flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        name: 🏷️ Type check with mypy
        additional_dependencies: [types-all]
        args: [--ignore-missing-imports]

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        name: 🔒 Security check with bandit
        args: ['-c', 'pyproject.toml']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        name: ✂️ Trim trailing whitespace
      - id: end-of-file-fixer
        name: 📝 Fix end of files
      - id: check-yaml
        name: ✅ Check YAML
      - id: check-added-large-files
        name: 📏 Check for large files
        args: ['--maxkb=500']
      - id: check-json
        name: 🔍 Check JSON
      - id: check-toml
        name: 🔍 Check TOML
